Repository rustedpy/result, pull requests merged in 2021-12, with the labels that each got.

#78 Implement Ok.unwrap_or_else and Err.unwrap_or_else
  README.rst
  result/result.py
  tests/test_result.py
Labels: enhancement

#80 add tox configuration for easy local development
  .gitignore
  pyproject.toml
  tox.ini
Labels: enhancement, chore

#79 Move to a src/ dir based project layout
  pyproject.toml
  setup.cfg
  src/result/__init__.py
  src/result/py.typed
  src/result/result.py
Labels: chore

#81 Update changelog to include unwrap_or_else
  CHANGELOG.md
Labels: chore

#83 Adopt PEP 563 postponed annotation evaluation
  src/result/result.py
  tests/test_pattern_matching.py
  tests/test_result.py
Labels: enhancement, chore

#84 bump mypy in dev requirements
  requirements-dev.txt
Labels: chore

#71 Add decorator to turn regular functions in Result returning ones
  CHANGELOG.md
  README.rst
  setup.cfg
  src/result/__init__.py
  src/result/result.py
  tests/test_result.py
Labels: enhancement
